// Code generated by MockGen. DO NOT EDIT.
// Source: subscriptionservice.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	dto "efmob/internal/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositories is a mock of Repositories interface.
type MockRepositories struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoriesMockRecorder
}

// MockRepositoriesMockRecorder is the mock recorder for MockRepositories.
type MockRepositoriesMockRecorder struct {
	mock *MockRepositories
}

// NewMockRepositories creates a new mock instance.
func NewMockRepositories(ctrl *gomock.Controller) *MockRepositories {
	mock := &MockRepositories{ctrl: ctrl}
	mock.recorder = &MockRepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositories) EXPECT() *MockRepositoriesMockRecorder {
	return m.recorder
}

// DeleteSubscriptionInfo mocks base method.
func (m *MockRepositories) DeleteSubscriptionInfo(arg0 context.Context, arg1 dto.DeleteSubscriptionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionInfo indicates an expected call of DeleteSubscriptionInfo.
func (mr *MockRepositoriesMockRecorder) DeleteSubscriptionInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionInfo", reflect.TypeOf((*MockRepositories)(nil).DeleteSubscriptionInfo), arg0, arg1)
}

// InsertSubscriptionInfo mocks base method.
func (m *MockRepositories) InsertSubscriptionInfo(arg0 context.Context, arg1 dto.CreateOrUpdateSubscriptionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSubscriptionInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertSubscriptionInfo indicates an expected call of InsertSubscriptionInfo.
func (mr *MockRepositoriesMockRecorder) InsertSubscriptionInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSubscriptionInfo", reflect.TypeOf((*MockRepositories)(nil).InsertSubscriptionInfo), arg0, arg1)
}

// ListSubscriptionsByUserID mocks base method.
func (m *MockRepositories) ListSubscriptionsByUserID(arg0 context.Context, arg1 string, arg2, arg3 int) ([]dto.SubscriptionListItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptionsByUserID", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]dto.SubscriptionListItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSubscriptionsByUserID indicates an expected call of ListSubscriptionsByUserID.
func (mr *MockRepositoriesMockRecorder) ListSubscriptionsByUserID(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptionsByUserID", reflect.TypeOf((*MockRepositories)(nil).ListSubscriptionsByUserID), arg0, arg1, arg2, arg3)
}

// PatchSubscriptionInfo mocks base method.
func (m *MockRepositories) PatchSubscriptionInfo(arg0 context.Context, arg1 dto.PatchSubscriptionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchSubscriptionInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchSubscriptionInfo indicates an expected call of PatchSubscriptionInfo.
func (mr *MockRepositoriesMockRecorder) PatchSubscriptionInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchSubscriptionInfo", reflect.TypeOf((*MockRepositories)(nil).PatchSubscriptionInfo), arg0, arg1)
}

// SumSubscriptionPriceByFilter mocks base method.
func (m *MockRepositories) SumSubscriptionPriceByFilter(arg0 context.Context, arg1, arg2, arg3, arg4 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumSubscriptionPriceByFilter", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumSubscriptionPriceByFilter indicates an expected call of SumSubscriptionPriceByFilter.
func (mr *MockRepositoriesMockRecorder) SumSubscriptionPriceByFilter(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumSubscriptionPriceByFilter", reflect.TypeOf((*MockRepositories)(nil).SumSubscriptionPriceByFilter), arg0, arg1, arg2, arg3, arg4)
}

// UpdateSubscriptionInfo mocks base method.
func (m *MockRepositories) UpdateSubscriptionInfo(arg0 context.Context, arg1 dto.CreateOrUpdateSubscriptionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionInfo indicates an expected call of UpdateSubscriptionInfo.
func (mr *MockRepositoriesMockRecorder) UpdateSubscriptionInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionInfo", reflect.TypeOf((*MockRepositories)(nil).UpdateSubscriptionInfo), arg0, arg1)
}
